glcm:
- Autocorrelation
- JointAverage
- ClusterProminence
- ClusterShade
- ClusterTendency
- Contrast
- Correlation
- DifferenceAverage
- DifferenceEntropy
- DifferenceVariance
- JointEnergy
- JointEntropy
- Imc1
- Imc2
- Idm
- Idmn
- Id
- Idn
- InverseVariance
- MaximumProbability
- SumAverage
- SumEntropy
- SumSquares
first_order:
- Energy
- Entropy
- InterquartileRange
- Kurtosis
- MAD
- Maximum
- Mean
- Median
- Minimum
- NintiethPercentile
- Range
- rM
- RMS
- Skewness
- StandardDeviation
- TenthPercentile
- Uniformity
- Variance
