firstorder:
- 10Percentile
- 90Percentile
- Energy
- Entropy
- InterquartileRange
- Kurtosis
- Maximum
- MeanAbsoluteDeviation
- Mean
- Median
- Minimum
- Range
- RobustMeanAbsoluteDeviation
- RootMeanSquared
- Skewness
- TotalEnergy
- Uniformity
- Variance

shape:
- Elongation
- Flatness
- LeastAxisLength
- MajorAxisLength
- Maximum2DDiameterColumn
- Maximum2DDiameterRow
- Maximum2DDiameterSlice
- Maximum3DDiameter
- MeshVolume
- MinorAxisLength
- Sphericity
- SurfaceArea
- SurfaceVolumeRatio
- VoxelVolume

glcm:
- Autocorrelation
- ClusterProminence
- ClusterShade
- ClusterTendency
- Contrast
- Correlation
- DifferenceAverage
- DifferenceEntropy
- DifferenceVariance
- Id
- Idm
- Idmn
- Idn
- Imc1
- Imc2
- InverseVariance
- JointAverage
- JointEnergy
- JointEntropy
- MCC
- MaximumProbability
- SumAverage
- SumEntropy
- SumSquares

gldm:
- DependenceEntropy
- DependenceNonUniformity
- DependenceNonUniformityNormalized
- DependenceVariance
- GrayLevelNonUniformity
- GrayLevelVariance
- HighGrayLevelEmphasis
- LargeDependenceEmphasis
- LargeDependenceHighGrayLevelEmphasis
- LargeDependenceLowGrayLevelEmphasis
- LowGrayLevelEmphasis
- SmallDependenceEmphasis
- SmallDependenceHighGrayLevelEmphasis
- SmallDependenceLowGrayLevelEmphasis

glrlm:
- GrayLevelNonUniformity
- GrayLevelNonUniformityNormalized
- GrayLevelVariance
- HighGrayLevelRunEmphasis
- LongRunEmphasis
- LongRunHighGrayLevelEmphasis
- LongRunLowGrayLevelEmphasis
- LowGrayLevelRunEmphasis
- RunEntropy
- RunLengthNonUniformity
- RunLengthNonUniformityNormalized
- RunPercentage
- RunVariance
- ShortRunEmphasis
- ShortRunHighGrayLevelEmphasis
- ShortRunLowGrayLevelEmphasis
glszm:
- GrayLevelNonUniformity
- GrayLevelNonUniformityNormalized
- GrayLevelVariance
- HighGrayLevelZoneEmphasis
- LargeAreaEmphasis
- LargeAreaHighGrayLevelEmphasis
- LargeAreaLowGrayLevelEmphasis
- LowGrayLevelZoneEmphasis
- SizeZoneNonUniformity
- SizeZoneNonUniformityNormalized
- SmallAreaEmphasis
- SmallAreaHighGrayLevelEmphasis
- SmallAreaLowGrayLevelEmphasis
- ZoneEntropy
- ZonePercentage
- ZoneVariance
ngtdm:
- Busyness
- Coarseness
- Complexity
- Contrast
- Strength
