repos:
# simple checks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-added-large-files
    args: [--maxkb=500]
  - id: check-json
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: pretty-format-json
    args: [--autofix, --no-sort-keys]
  - id: trailing-whitespace

# format yaml
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.2
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --implicit_start]

# format shell scripts
- repo: https://github.com/cisagov/pre-commit-shfmt
  rev: v0.0.2
  hooks:
  - id: shfmt
    args:
    - --indent=2
    - --binary-next-line
    - --case-indent
    - --space-redirects

# format python code
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    args: [--line-length=120]

# type check python code
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    additional_dependencies:
    - pydantic
    - types-all
    args:
    - --python-version=3.10
    - --ignore-missing-imports
    - --no-strict-optional
    - --no-warn-no-return

# lint python code
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.275
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
