name: totalseg
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8.12
  - pip=21.2.4
  - pytorch==1.12.1
  - torchvision
  - cudatoolkit=11.6
  - pip:
    - -r requirements.txt
